package org.javacore.reflection;

public class MainTest2 {
    public static void main(String[] args) throws Exception{
        System.out.println("被调用");
        Thread.sleep(3000);
        System.out.println("被调结束");
    }
}
